// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CliApp is an autogenerated mock type for the CliApp type
type CliApp struct {
	mock.Mock
}
