name: Go

on:
  push:
    branches:
      - "master"
      - "feature/**"
      - "hotfix/**"
      - "bugfix/**"
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install revive
        run: go install github.com/mgechev/revive@latest

      - name: Lint
        run: revive -config revive.toml -exclude vendor/... -formatter friendly ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
